
[functions.send-order-pdf]
enabled = true
verify_jwt = false
import_map = "./functions/send-order-pdf/deno.json"
entrypoint = "./functions/send-order-pdf/index.ts"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-order/*.html" ]
